<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ocls</string>
	</array>
	<key>name</key>
	<string>OcellusScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.ocls</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>```</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>comment.block.documentation.ocls</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(takes|returns|return|import|match)\b</string>
			<key>name</key>
			<string>keyword.control.ocls</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.ocls</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.ocls</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class|type|module)\s+(\w+)+\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.ocls</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.ocls</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(shadowtype)\s+(\w+)+\s+=\s+(String|Integer|Char|Boolean|Float|Callable|Anything|Nothing);</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(var)\s+(\w+)+\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.readwrite.ocls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(let)\s+(\w+)+\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.constant.ocls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(private)\b</string>
			<key>name</key>
			<string>storage.type.ocls</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(func)\s+(\w+)+\s+(takes)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ocls</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ocls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ocls</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>variable.language.ocls</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(func)\s+(\w+)+\s+=\s+\((\w+(,\s+\w+)*)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ocls</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ocls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+=</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.ocls</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Z]+(\w+)+)\(</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9])+\b</string>
			<key>name</key>
			<string>constant.numeric.ocls</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(String|Char|Integer|Float|List|Callable|Boolean|true|false)\b</string>
			<key>name</key>
			<string>constant.language.ocls</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(lambda)\s+(\w+)+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ocls</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ocls</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\:</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ocellusscript</string>
	<key>uuid</key>
	<string>3A3DA406-18E5-4E88-8B99-08983B148358</string>
</dict>
</plist>
