/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package net.marquiskurt.ocls.compiler

import OSTokenizer


class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val x = OSTokenizer("E")
    println(x.tokenizeAll())
}
