/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package net.marquiskurt.ocls.compiler

import java.io.File
import com.xenomachina.argparser.ArgParser


import OSTokenizer
import TokenType


class NOC(val files: List<File>?) {

    private var script = ""
    private var tokenizer = OSTokenizer(this.script)

    @ExperimentalStdlibApi
    fun tokenize(): List<Pair<TokenType?, String?>?> {
        return this.tokenizer.tokenizeAll()
    }

}

// TODO: Process a directory or files with arguments
@ExperimentalStdlibApi
fun main(args: Array<String>) {
    println("TODO: Get this to make token files!")
}
