/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package net.marquiskurt.ocls.compiler

import OSTokenizer


class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

@ExperimentalStdlibApi
fun main() {
    val x = OSTokenizer("import this;")
    println(x.tokenizeAll())
}
