name: Tests
on: push

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversions:
          - '2.7.17'
          - '3.7.6'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversions }}
          architecture: 'x64'
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies and test
        run: |
          poetry install
          poetry run python -m pytest tests/ -vv