name: Tests
on: push

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversions:
          - '2.7'
          - '3.7'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversions }}
          architecture: 'x64'
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          exec bash
        shell: bash
      - name: Run tests
        run: |
          poetry install
          ./tests/test_lexer.py