name: Tests
on: push

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversions:
          - '2.7'
          - '3.7'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversions }}
          architecture: 'x64'
      - name: Setup Poetry dependencies
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: join("python", matrix.pyversions)
          poetry_version: 1.0.3
          args: install
      - name: Run tests
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: join("python", matrix.pyversions)
          poetry_version: 1.0.3
          args: run ./tests/test_lexer.py